import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from './layout/Header';
import Footer from './layout/Footer';

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="ko">
		<body className={`${geistSans.variable} ${geistMono.variable}`}>
			{children}
			<Header></Header>
			<main></main>
			{/* <Footer></Footer> */}
		</body>
		</html>
	);
};